# Site settings
title: Jekyll Oneweb
author:
  name: Seth Warburton
  email: seth@internet-inspired.com
  twitter_username: nternetinspired
  github_username:  nternetinspired

client:
  name: Client Name
  logo: /img/client-logo.png
  sample-h1: A sample header
  sample-h2: An example of a sub-header
  sample-adjective-1: Jekyll
  sample-adjective-2: Sassmeister
  sample-adjective-3: mumblecore
  sample-adjective-4: Intelligentsia
  sample-adjective-5: Chillwave
  sample-adjective-6: tofu
  sample-buttontext-1: Primary button
  sample-buttontext-2: Default button
  sample-blockquote: A quote, or testimonial is a great way to exemplify your business success and make the most of available material.
  sample-cite: Me - I just said that.
  sample-cta: This is <em>your</em> call to action
  sample-cta-button: Get started!
  sample-p-1: Carles chambray quinoa shabby chic tattooed High Life, literally tofu. This sample paragraph has <strong>strong parts</strong> and <em>emphasized parts</em>. Readymade vinyl food truck, mlkshk messenger bag slow-carb plaid Shoreditch Schlitz.
  sample-p-2: Narwhal fap hella plaid selfies polaroid. Kogi Blue Bottle fap, <a class="typography-sample-a" href="#">retro skateboard bitters</a> sriracha pork belly Williamsburg PBR dreamcatcher vinyl Bushwick Kickstarter VHS.
  sample-p-3: Helvetica Banksy photo booth, jean shorts cray locavore ugh Carles fanny pack sartorial Cosby sweater. Yr synth beard, actually DIY flannel gentrify hella Kickstarter polaroid. Flexitarian direct trade Bushwick VHS banh mi salvia deep v, crucifix hashtag gluten-free single-origin coffee Shoreditch Austin Portland.
  sample-link-1: This is an example of link text.

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/jekyll-design" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yourusername
github_username:  yourusername

# Compress html
compress_html:
  clippings: ['!--', html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]

# Build settings
markdown: kramdown
permalink: /:categories/:title
sass:
    style: :compressed
